[workspace]
resolver = "3"
members = [
    # Wine
    "protocol",
    "windows-kernel",
    "loader",
    "windows",
    # DLLs
    "dll/ntdll",
    # Tools
]

[workspace.dependencies]
errno = "0.3.14"
libc = "1.0.0-alpha.3"
log = "0.4.29"
mach-sys = "0.5.4"
packed_ptr = "0.1.2"
protocol = { path = "protocol" }
windows = { path = "windows" }
